version: "2.3"

services:
  app:
    build: .
    container_name: laravel-app
    volumes:
      - .:/var/www
    networks:
      - laravel-network
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build: .docker/nginx
    container_name: laravel-nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - laravel-network
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: laravel-redis
    expose:
      - 6379
    networks:
      - laravel-network

  db:
    image: mysql:5.7
    container_name: laravel-db
    restart: always
    tty: true
    command: --innodb-use-native-aio=0
    ports:
      - "3306:3306"
    networks:
      - laravel-network
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mysql -uroot --database=laravel --password=root --execute="select count(*) from information_schema.tables"',
        ]
      interval: 5s
      timeout: 5s
      retries: 4

networks:
  laravel-network:
    driver: bridge
