apiVersion: apps/v1 #versao da api do kubernets
kind: Deployment
metadata: 
  name: hello-nginx
spec:
  selector:
    matchLabels:
      app: hello-nginx
  replicas: 6
  template: # configuracao do pod
    metadata:
      labels: # forma de identificar os pods
        app: hello-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-conf
          readOnly: true
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            cpu: "250m"
            memory: "250Mi" # se passar do limite configurado, o pod é derrubado

      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf