apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache-hpa
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef: # escolhendo qual deployment ira ser escalavel
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: php-apache-hpa #nome do deployment
  targetCPUUtilizationPercentage: 20 #porcento da cpu
    